# Generated by Django 4.2.13 on 2024-07-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("economia", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="childcomments", options={"managed": True},),
        migrations.AlterModelOptions(name="player", options={"managed": True},),
    ]
