# Generated by Django 4.2.13 on 2024-07-26 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("economia", "0003_alter_childcomments_options_player_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="subjects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="economia.subjects"
            ),
        ),
    ]
